apiVersion: v1
kind: Service
metadata:
  name: ollama-html-ui-service
  labels:
    app: ollama-html-ui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: ollama-html-ui
